import re

def clean_text(text: str) -> str:
    """
    Cleans and normalizes raw OCR text output.
    Removes common OCR artifacts and excessive whitespace while safely 
    preserving markdown formatting and LaTeX/mathematical syntax.
    """
    if not text or not isinstance(text, str):
        return ""
        
    # 1. Strip non-printable control characters (often generated by OCR glitches)
    # This regex removes ASCII control chars but safely preserves \n (newline) and \t (tab)
    text = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', text)
    
    # 2. Normalize horizontal whitespace
    # Replaces multiple consecutive spaces or tabs with a single space
    # (Does not affect newlines)
    text = re.sub(r'[ \t]+', ' ', text)
    
    # 3. Normalize vertical whitespace
    # OCR engines often output 4 or 5 newlines for a single gap. 
    # This caps consecutive newlines to a maximum of 2 (a standard paragraph break).
    text = re.sub(r'\n{3,}', '\n\n', text)
    
    # 4. Fix common stray spaces around line breaks created by OCR
    text = re.sub(r' \n', '\n', text)
    text = re.sub(r'\n ', '\n', text)
    
    # 5. Final strip of leading/trailing whitespace
    return text.strip()